### ISSUE TITLE
Blueberry (and Raspberry): Change default yield and add to static data

### ISSUE THREAD

**Issue by joandrews** [bcgov/nmp-arm#72]
As a blueberry grower, I want the calculator to default to a reasonable yield, so that I don't have to do research if I do not know my current yield

![Image](https://github.com/bcgov/nmp-arm/assets/47464456/f35d4471-64a3-40a7-ad8f-5ec17b4becbe)

**Additional Context**
- Only change the default yield for the blueberry pathway, on the Crop Details screen
- Add default yield to static data for both blueberry and raspberry - there should already be static data with default yield in the database

**Acceptance Criteria**
- [ ] The yield for blueberries defaults to 5 tons/ac on the Crop Details screen, instead of the current default of 7 tons/acre
- [ ] The default yield is added to static data, so AF can change the default yield in the future
- [ ] The default yield for the Raspberry pathway (5 tons/ac) is also added to static data, so AF can change it in the future

**Comment by LolandaE** [comment]
Created under wrong repo. Replaced by ticket #627.
